### ISSUE TITLE
Amplifier :: Prototype 2 :: M1 Power Supply - capacitors and design 

### ISSUE THREAD

**Issue by iqrohan** [iquesters/embedded#3]
1. All 10 nF capacitors to be made 0.1 uF having ceramic package.
2. Make layout smaller and compact.
3. Connectors to be put at the edges of the board.

**Comment by iqsourav** [comment]
1. All 10 nF capacitors on M1 are changed to 0.1 uF having ceramic package.
2. Layout is smaller and compact than previous version.
3. Connectors are at the edges of the board.

Done... Ready for checking.
