### ISSUE TITLE
Amplifier :: Prototype 2 :: Enhancements

### ISSUE THREAD

**Issue by iqrohan** [iquesters/embedded#6]
**Schematic**
1. Power Supply: 9V from +15V line using 7809. Power LED
2. Distortion: Add LED circuit using BC547
3. Power Amp: Add Master Volume circuit

**Layout**
1. Add mounting holes on all boards.
2. Route for all added components in the schematic

**Comment by iqrohan** [comment]
@iqsourav : In Power Amp Module change the AUX IN and Headphone Sockets to 3.5 mm stereo ones. Make necessary changes to schematic and layout files.

**Comment by iqsourav** [comment]
Schematic
1. Power Supply: 9V from +15V line using 7809. Power LED
2. Distortion: Added LED circuit using BC547
3. Power Amp: Added Master Volume circuit

Layout
1. Added mounting holes on all boards.
2. Routed all added components in the schematic/layout.

Aux IN done by 3.5mm scoket but headphone issue not closed yet.

**Comment by iqsourav** [comment]
Added 1/4" socket into latest Design temporarily.
